on:
  push:
    branches: [master]
  pull_request:
name: coverage
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --timeout 120 --out Xml
        env:
          TEST_HOST: greenmail
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
    services:
      greenmail:
        image: greenmail/standalone:1.6.8
        ports:
          - 3025:3025
          - 3110:3110
          - 3143:3143
          - 3465:3465
          - 3993:3993
          - 3995:3995
        env:
          GREENMAIL_OPTS: "-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose"
